spring:
   profiles:
      active: panji
---
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  config:
    activate:
      on-profile: panji
  application:
    name: Panji
  datasource:
      url: jdbc:postgresql://localhost:5432/CG
      username: postgres
      password: 123456
      driverClassName: org.postgresql.Driver
      hikari:
        minimumIdle: 2 
        maximumPoolSize: 30
        idleTimeout: 120000
        connectionTimeout: 300000
        leakDetectionThreshold: 300000
  jpa: 
      database: default
      hibernate: 
         dialect: org.hibernate.dialect.PostgreSQLDialect
         ddl-auto: update
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0
server:
  max-http-header-size: 10MB
  port: 8223
  error:
    whitelabel:
      enabled: false
    path: /error
  servlet:
    session:
        timeout: PT30M
URL:
  FILE_IN: "X://"
---
